language: php

php:
    - 5.4
    - 5.5
    - 5.6
    - hhvm

install:
    - composer self-update
    - composer global require codeclimate/php-test-reporter
    - composer install
script:
    - phpunit --coverage-clover build/logs/clover.xml
